### ISSUE TITLE
Service interruption after several days

### ISSUE THREAD

**Issue by isaacdecoded** [cloudamqp/lavinmq#510]
Hello,

I've experienced service interruption twice after several days have passed (~12 days). Checking some logs I've seen that this interruption lasted more than one minute so in terms of reliability this is a big impact on Event-based services, being the case.

Is this an expected behavior or something are you working on?

Thanks in advance,
I.

**Comment by kickster97** [comment]
Hi Isaac, what version of LavinMQ are you running? Do you know the cause of the interruption?

**Comment by kickster97** [comment]
Also, are you using CloudAMQP or are you hosting independently?

**Comment by kickster97** [comment]
If you are currently utilizing CloudAMQP to host your service, it's important to carefully consider the plan that your service is operating on. We advise against using shared plans such as Lemming or Ermine for production services, as the performance can vary and unexpected interruptions may occur during server maintenance. It's possible that you may have experienced downtime due to a recent version upgrade.

If you're looking for better reliability and stability, we recommend upgrading to a dedicated server. With a dedicated server, maintenance activities can be scheduled according to your preferences, leading to better predictability and fewer disruptions to your service.

**Comment by isaacdecoded** [comment]
Hi, Christina,

Yes, you're right, I'm testing on a shared plan, so based on what you said and the info you have on the website, these interruptions are expected behavior. Sorry I haven't get it before opening the issue.

I'll close the issue and will check another plan for production purposes.

Thanks so much,
I.
